pre-push:
  parallel: true
  commands:
    to-native-lint:
      root: "apps/native/"
      glob: "*.{js,jsx,ts,tsx}"
      run: pnpm eslint --fix {push_files}

    to-native-format:
      root: "apps/native/"
      glob: "*.{js,jsx,ts,tsx}"
      run: pnpm prettier --write --ignore-unknown {push_files}
